# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 612)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(52, 52, 52);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.outputLabel.setFont(font)
        self.outputLabel.setStyleSheet("background-color: rgb(199, 199, 199);\n"
"color: rgb(6, 6, 6);")
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("%"))
        self.percButton.setGeometry(QtCore.QRect(10, 120, 100, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        self.percButton.setFont(font)
        self.percButton.setStyleSheet("background-color: rgb(2, 2, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 5px;")
        self.percButton.setObjectName("percButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pressed("C"))
        self.cButton.setGeometry(QtCore.QRect(130, 120, 100, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.cButton.setFont(font)
        self.cButton.setStyleSheet("background-color: rgb(2, 2, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 5px;")
        self.cButton.setObjectName("cButton")
        self.DelButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.delete())
        self.DelButton.setGeometry(QtCore.QRect(250, 120, 100, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.DelButton.setFont(font)
        self.DelButton.setStyleSheet("background-color: rgb(2, 2, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 5px;")
        self.DelButton.setObjectName("DelButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("7"))
        self.sevenButton.setGeometry(QtCore.QRect(20, 210, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.sevenButton.setFont(font)
        self.sevenButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.sevenButton.setObjectName("sevenButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 210, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.eightButton.setFont(font)
        self.eightButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("9"))
        self.nineButton.setGeometry(QtCore.QRect(180, 210, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.nineButton.setFont(font)
        self.nineButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.nineButton.setObjectName("nineButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("/"))
        self.divideButton.setGeometry(QtCore.QRect(260, 210, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.divideButton.setFont(font)
        self.divideButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.divideButton.setObjectName("divideButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 300, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.fiveButton.setFont(font)
        self.fiveButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.fiveButton.setObjectName("fiveButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("4"))
        self.fourButton.setGeometry(QtCore.QRect(20, 300, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.fourButton.setFont(font)
        self.fourButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.fourButton.setObjectName("fourButton")
        self.MultiplyButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("*"))
        self.MultiplyButton.setGeometry(QtCore.QRect(260, 300, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.MultiplyButton.setFont(font)
        self.MultiplyButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.MultiplyButton.setObjectName("MultiplyButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("6"))
        self.sixButton.setGeometry(QtCore.QRect(180, 300, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.sixButton.setFont(font)
        self.sixButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.sixButton.setObjectName("sixButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 390, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.twoButton.setFont(font)
        self.twoButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.twoButton.setObjectName("twoButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("1"))
        self.oneButton.setGeometry(QtCore.QRect(20, 390, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.oneButton.setFont(font)
        self.oneButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.oneButton.setObjectName("oneButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("-"))
        self.minusButton.setGeometry(QtCore.QRect(260, 390, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.minusButton.setFont(font)
        self.minusButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.minusButton.setObjectName("minusButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("3"))
        self.threeButton.setGeometry(QtCore.QRect(180, 390, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.threeButton.setFont(font)
        self.threeButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.threeButton.setObjectName("threeButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("0"))
        self.zeroButton.setGeometry(QtCore.QRect(100, 480, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.zeroButton.setFont(font)
        self.zeroButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.zeroButton.setObjectName("zeroButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.pressed("."))
        self.dotButton.setGeometry(QtCore.QRect(20, 480, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.dotButton.setFont(font)
        self.dotButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.dotButton.setObjectName("dotButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.evaluate())
        self.equalButton.setGeometry(QtCore.QRect(180, 480, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.equalButton.setFont(font)
        self.equalButton.setStyleSheet("\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(75, 181, 67);\n"
"border-style: outset;\n"
"border-radius: 10px;\n"
"")
        self.equalButton.setObjectName("equalButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.pressed("+"))
        self.plusButton.setGeometry(QtCore.QRect(260, 480, 75, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.plusButton.setFont(font)
        self.plusButton.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-radius: 10px;")
        self.plusButton.setObjectName("plusButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def pressed(self, press):
            if press == "C":
                    return self.outputLabel.setText("0")
            else:
                    if self.outputLabel.text() == "0":
                            self.outputLabel.setText("")
                    return self.outputLabel.setText(f"{self.outputLabel.text()}{press}")
    def delete(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]
        return self.outputLabel.setText(screen)
    def evaluate(self):
        screen = self.outputLabel.text()
        try:
                sol = eval(screen)
                return self.outputLabel.setText(str(sol))
        except:
                return self.outputLabel.setText("ERROR")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.DelButton.setText(_translate("MainWindow", "Del"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.MultiplyButton.setText(_translate("MainWindow", "x"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.dotButton.setText(_translate("MainWindow", "."))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.plusButton.setText(_translate("MainWindow", "+"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
